name: Docker Build, Scan, and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ap-south-1

        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 957007732222.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t github .

    - name: Push Docker Image
      run: |
        docker tag github:latest 957007732222.dkr.ecr.ap-south-1.amazonaws.com/github:latest
        docker push 957007732222.dkr.ecr.ap-south-1.amazonaws.com/github:latest

    - name: Deploy Docker Container
      if: success()
      run: |
        # Additional steps for deploying your Docker container
        # For example, you can use docker-compose or Docker run commands here
        # Replace the following line with your actual deployment command
        docker run -d -p 8080:80 957007732222.dkr.ecr.ap-south-1.amazonaws.com/github:latest
        echo "Docker container deployed successfully."

    - name: Notify on Success
      if: success()
      run: echo "Docker image successfully built, pushed, and container deployed to AWS ECR!"

    - name: Notify on Failure
      if: failure()
      run: echo "Failed to build, push, or deploy Docker image to AWS ECR!"

